import 'dart:convert';
import 'dart:io';

final Map<String, List<String>> verbTranslations = {
  "eats": ["memakan"],
  "has": ["memiliki"],
  "flies over": ["terbang di atas"],
  "swallows": ["menelan"],
  "protects": ["melindungi"],
  "blocks": ["menghadang"],
  "resists": ["menolak"],
  "in": ["di dalam"],
  "captures": ["menangkap"],
  "above": ["di atas"],
  "houses": ["menampung"],
  "uses": ["menggunakan"],
  "survives": ["bertahan hidup dari"],
  "contains": ["berisi"],
  "inspires": ["menginspirasi"],
  "incinerates": ["membakar"],
  "on": ["di atas"],
  "explodes": ["meledakkan"],
  "drinks": ["meminum"],
  "kills": ["membunuh"],
  "pricier than": ["lebih mahal dari"],
  "burns": ["membakar"],
  "cleans": ["membersihkan"],
  "outclasses": ["mengungguli"],
  "carries": ["membawa"],
  "over": ["di atas"],
  "sweeps away": ["menyapu bersih"],
  "scares": ["menakuti"],
  "reflects": ["memantulkan"],
  "about": ["tentang"],
  "before": ["sebelum"],
  "attracts": ["menarik"],
  "looks at": ["melihat"],
  "conducts": ["menghantarkan"],
  "lives on": ["tinggal di"],
  "shoots": ["menembak"],
  "crushes": ["menghancurkan"],
  "makes": ["membuat"],
  "disturbs": ["mengganggu"],
  "chops": ["memotong"],
  "warms": ["menghangatkan"],
  "costs": ["membutuhkan biaya"],
  "vaporizes": ["menguapkan"],
  "confuses": ["membingungkan"],
  "breaks": ["memecahkan"],
  "breathes": ["menghirup"],
  "claims": ["mengklaim"],
  "strikes": ["menyerang"],
  "powers": ["memberi daya pada"],
  "bans": ["melarang"],
  "traps": ["menjebak"],
  "teaches about": ["mengajarkan tentang"],
  "owns": ["memiliki"],
  "stains": ["menodai"],
  "funds": ["mendanai"],
  "creates": ["membuat"],
  "causes": ["menyebabkan"],
  "short-circuits": ["membuat korsleting pada"],
  "has no": ["tidak memiliki"],
  "beats": ["mengalahkan"],
  "wins": ["menang atas"],
  "draw": ["seri melawan"],
  "draws": ["seri melawan"],
  "outruns": ["berlari lebih cepat dari"],
  "outlives": ["hidup lebih lama dari"],
  "outsmarts": ["mengakali"],
  "outflies": ["terbang lebih cepat dari"],
  "outperforms": ["tampil lebih baik dari"],
  "penetrates": ["menembus"],
  "stabs": ["menusuk"],
  "slices": ["mengiris"],
  "dices": ["memotong dadu"],
  "guts": ["mengeluarkan isi perut"],
  "minces": ["mencincang"],
  "juliennes": ["memotong korek api"],
  "smooshes": ["meremukkan"],
  "squishes": ["memenyekkan"],
  "smashes": ["menghancurkan"],
  "topples": ["merobohkan"],
  "ruins": ["merusak"],
  "prevents": ["mencegah"],
  "poisons": ["meracuni"],
  "chokes": ["mencekik"],
  "strangles": ["mencekik"],
  "drowns": ["menenggelamkan"],
  "suffocates": ["membuat sesak napas"],
  "extinguishes": ["memadamkan"],
  "dissolves": ["melarutkan"],
  "erodes": ["mengikis"],
  "rusts": ["membuat berkarat"],
  "corrodes": ["mengaratkan"],
  "freezes": ["membekukan"],
  "shatters": ["menghancurkan"],
  "cuts": ["memotong"],
  "clips": ["memotong"],
  "tears": ["merobek"],
  "shreds": ["mencabik-cabik"],
  "splits": ["membelah"],
  "cracks": ["meretakkan"],
  "pulverizes": ["melumatkan"],
  "grinds": ["menggiling"],
  "flattens": ["meratakan"],
  "squashes": ["meremas"],
  "tramples": ["menginjak-injak"],
  "melts": ["melelehkan"],
  "heats": ["memanaskan"],
  "boils": ["mendidihkan"],
  "evaporates": ["menguapkan"],
  "dries": ["mengeringkan"],
  "dehydrates": ["mendehidrasi"],
  "absorbs": ["menyerap"],
  "soaks": ["merendam"],
  "sops up": ["menyerap"],
  "spills": ["menumpahkan"],
  "leaks": ["membocorkan"],
  "floods": ["membanjiri"],
  "submerges": ["menenggelamkan"],
  "swamps": ["membanjiri"],
  "dampens": ["melembabkan"],
  "blocks": ["menghadang"],
  "reflects": ["memantulkan"],
  "deflects": ["menangkis"],
  "conducts": ["menghantarkan"],
  "diverts": ["mengalihkan"],
  "attracts": ["menarik"],
  "repels": ["menolak"],
  "magnetizes": ["memagnetkan"],
  "charges": ["mengisi daya"],
  "shocks": ["menyengat"],
  "electrocutes": ["menyetrum"],
  "blind": ["membutakan"],
  "blinds": ["membutakan"],
  "deafens": ["memekakkan"],
  "silences": ["membungkam"],
  "muffles": ["meredam"],
  "damps": ["meredam"],
  "quiets": ["menenangkan"],
  "soothes": ["menenangkan"],
  "calms": ["menenangkan"],
  "frightens": ["menakuti"],
  "terrifies": ["mengerikan"],
  "intimidates": ["mengintimidasi"],
  "startles": ["mengejutkan"],
  "alarms": ["mencemaskan"],
  "warns": ["peringatan"],
  "alerts": ["waspada"],
  "signals": ["sinyal"],
  "indicates": ["mengindikasikan"],
  "reveals": ["mengungkapkan"],
  "detects": ["mendeteksi"],
  "finds": ["menemukan"],
  "spots": ["menemukan"],
  "locates": ["menemukan"],
  "traces": ["melacak"],
  "follows": ["mengikuti"],
  "chases": ["mengejar"],
  "pursues": ["mengejar"],
  "catches": ["menangkap"],
  "traps": ["menjebak"],
  "snares": ["menjebak"],
  "ensnares": ["menjebak"],
  "tangles": ["kusut"],
  "entangles": ["menjerat"],
  "binds": ["mengikat"],
  "ties": ["mengikat"],
  "straps": ["mengikat"],
  "lashes": ["mencambuk"],
  "whips": ["mencambuk"],
  "hits": ["memukul"],
  "pounds": ["menumbuk"],
  "bashes": ["menghantam"],
  "batters": ["menghantam"],
  "fractures": ["retak"],
  "splinters": ["hancur berkeping-keping"],
  "chips": ["serpihan"],
  "nicks": ["goresan"],
  "scratches": ["menggores"],
  "carves": ["mengukir"],
  "slashes": ["menebas"],
  "pierces": ["menembus"],
  "drills": ["mengebor"],
  "bores": ["mengebor"],
  "digs": ["menggali"],
  "scoops": ["menyendok"],
  "scrapes": ["mengikis"],
  "shaves": ["mencukur"],
  "peels": ["mengupas"],
  "skins": ["menguliti"],
  "fillets": ["memotong fillet"],
  "shapes": ["membentuk"],
  "molds": ["mencetak"],
  "sculpts": ["memahat"],
  "builds": ["membangun"],
  "constructs": ["membangun"],
  "erects": ["mendirikan"],
  "forms": ["membentuk"],
  "fashions": ["membentuk"],
  "designs": ["merancang"],
  "plans": ["merencanakan"],
  "devises": ["merancang"],
  "invents": ["menemukan"],
  "originates": ["berasal dari"],
  "begins": ["memulai"],
  "initiates": ["memulai"],
  "launches": ["meluncurkan"],
  "triggers": ["memicu"],
  "prompts": ["mendorong"],
  "effects": ["mempengaruhi"],
  "yields": ["menghasilkan"],
  "affords": ["memberikan"],
  "supplies": ["memasok"],
  "furnishes": ["menyediakan"],
  "gives": ["memberikan"],
  "grants": ["memberikan"],
  "bestows": ["menganugerahkan"],
  "presents": ["menyajikan"],
  "offers": ["menawarkan"],
  "tenders": ["menawarkan"],
  "submits": ["menyerahkan"],
  "delivers": ["mengirimkan"],
  "hands": ["menyerahkan"],
  "passes": ["melewati"],
  "transfers": ["mentransfer"],
  "conveys": ["menyampaikan"],
  "transports": ["mengangkut"],
  "hauls": ["mengangkut"],
  "drags": ["menyeret"],
  "pulls": ["menarik"],
  "tows": ["menderek"],
  "tugs": ["menarik"],
  "jerks": ["menyentak"],
  "wrenches": ["merenggut"],
  "yanks": ["merenggut"],
  "snatches": ["merebut"],
  "grabs": ["merebut"],
  "seizes": ["merebut"],
  "takes": ["mengambil"],
  "retains": ["mempertahankan"],
  "preserves": ["melestarikan"],
  "defends": ["membela"],
  "shields": ["melindungi"],
  "covers": ["menutupi"],
  "hides": ["menyembunyikan"],
  "conceals": ["menyembunyikan"],
  "masks": ["menutupi"],
  "veils": ["menyelubungi"],
  "shelters": ["melindungi"],
  "harbors": ["menampung"],
  "lodges": ["menampung"],
  "boards": ["menumpang"],
  "accommodates": ["menampung"],
  "encloses": ["melampirkan"],
  "encases": ["membungkus"],
  "envelops": ["menyelimuti"],
  "packages": ["mengemas"],
  "boxes": ["mengotaki"],
  "crates": ["mengemas"],
  "bags": ["mengantongi"],
  "sacks": ["mengantongi"],
  "pockets": ["mengantongi"],
  "stores": ["menyimpan"],
  "stows": ["menyimpan"],
  "packs": ["mengemas"],
  "stuffs": ["menjejalkan"],
  "crams": ["menjejalkan"],
  "jams": ["menyumbat"],
  "presses": ["menekan"],
  "pinches": ["mencubit"],
  "tweaks": ["menyesuaikan"],
  "twists": ["memutar"],
  "spins": ["memutar"],
  "rotates": ["memutar"],
  "revolves": ["berputar"],
  "wheels": ["memutar"],
  "steers": ["mengarahkan"],
  "guides": ["memandu"],
  "escorts": ["mengawal"],
  "ushers": ["mengantar"],
  "points": ["menunjuk"],
  "focuses": ["memfokuskan"],
  "levels": ["meratakan"],
  "instructs": ["menginstruksikan"],
  "tutors": ["membimbing"],
  "coaches": ["melatih"],
  "exercises": ["melatih"],
  "practices": ["berlatih"],
  "studies": ["mempelajari"],
  "learns": ["belajar"],
  "spells": ["mengeja"],
  "defines": ["mendefinisikan"],
  "translates": ["menerjemahkan"],
  "interprets": ["menafsirkan"],
  "deciphers": ["menguraikan"],
  "solves": ["memecahkan"],
  "resolves": ["menyelesaikan"],
  "decides": ["memutuskan"],
  "chooses": ["memilih"],
  "selects": ["memilih"],
  "prefers": ["memilih"],
  "favors": ["mendukung"],
  "likes": ["menyukai"],
  "loves": ["mencintai"],
  "adores": ["memuja"],
  "venerates": ["memuliakan"],
  "esteems": ["menghargai"],
  "prizes": ["menghargai"],
  "treasures": ["menghargai"],
  "cherishes": ["menghargai"],
  "possesses": ["memiliki"],
  "belong": ["tergolong"],
  "belongs": ["tergolong"],
  "pertains": ["berkaitan"],
  "relates": ["berhubungan"],
  "refers": ["merujuk"],
  "concerns": ["menyangkut"],
  "applies": ["berlaku"],
  "fits": ["cocok"],
  "suits": ["cocok"],
  "agrees": ["setuju"],
  "conforms": ["menyesuaikan"],
  "complies": ["mematuhi"],
  "heeds": ["memperhatikan"],
  "observes": ["mengamati"],
  "fulfills": ["memenuhi"],
  "does": ["melakukan"],
  "discharges": ["membebaskan"],
  "meets": ["memenuhi"],
  "satisfies": ["memuaskan"],
  "answers": ["menjawab"],
  "suffices": ["mencukupi"],
  "works": ["bekerja"],
  "acts": ["bertindak"],
  "operates": ["beroperasi"],
  "functions": ["berfungsi"],
  "goes": ["pergi"],
  "proceeds": ["melanjutkan"],
  "progresses": ["maju"],
  "advances": ["maju"],
  "flows": ["mengalir"],
  "streams": ["mengalir"],
  "pours": ["menuangkan"],
  "gushes": ["memancar"],
  "showers": ["mandi"],
  "snows": ["bersalju"],
  "hails": ["menyambut"],
  "gusts": ["berembus"],
  "breezes": ["berembus"],
  "gales": ["badai"],
  "storms": ["menyerbu"],
  "coils": ["melingkar"],
  "spirals": ["melingkar"],
  "weaves": ["menenun"],
  "threads": ["menyusup"],
  "crosses": ["menyeberang"],
  "traverses": ["melintasi"],
  "spans": ["membentang"],
  "bridges": ["menjembatani"],
  "links": ["menghubungkan"],
  "joins": ["bergabung"],
  "unites": ["menyatukan"],
  "merges": ["menggabungkan"],
  "blends": ["memadukan"],
  "mingles": ["berbaur"],
  "associates": ["mengasosiasikan"],
  "combines": ["menggabungkan"],
  "aggregates": ["mengumpulkan"],
  "gathers": ["mengumpulkan"],
  "collects": ["mengumpulkan"],
  "accumulates": ["mengumpulkan"],
  "heaps": ["menimbun"],
  "loads": ["memuat"],
  "burdens": ["membebani"],
  "weighs": ["menimbang"],
  "oppresses": ["menindas"],
  "conquers": ["menaklukkan"],
  "vanquishes": ["menaklukkan"],
  "overcomes": ["mengatasi"],
  "surmounts": ["mengatasi"],
  "masters": ["menguasai"],
  "reigns": ["berkuasa"],
  "dominates": ["mendominasi"],
  "controls": ["mengendalikan"],
  "commands": ["memerintah"],
  "bosses": ["memerintah"],
  "dictates": ["mendikte"],
  "orders": ["memerintah"],
  "bids": ["menawarkan"],
  "calls": ["memanggil"],
  "invites": ["mengundang"],
  "asks": ["meminta"],
  "requests": ["meminta"],
  "begs": ["memohon"],
  "entreats": ["memohon"],
  "implores": ["memohon"],
  "pleads": ["memohon"],
  "prays": ["berdoa"],
  "supplicates": ["memohon"],
  "petitions": ["memohon"],
  "demands": ["menuntut"],
  "exacts": ["menuntut"],
  "insists": ["bersikeras"],
  "wants": ["menginginkan"],
  "wishes": ["berharap"],
  "craves": ["mendambakan"],
  "covets": ["menginginkan"],
  "envies": ["iri pada"],
  "grudges": ["mendendam"],
  "detests": ["membenci"],
  "abhors": ["membenci"],
  "loathes": ["membenci"],
  "avoids": ["menghindari"],
  "shuns": ["menghindari"],
  "evades": ["menghindari"],
  "escapes": ["melarikan diri dari"],
  "flees": ["melarikan diri dari"],
  "retreats": ["mundur"],
  "withdraws": ["menarik diri"],
  "leaves": ["meninggalkan"],
  "departs": ["berangkat"],
  "quits": ["keluar"],
  "abandons": ["meninggalkan"],
  "forsakes": ["meninggalkan"],
  "deserts": ["meninggalkan"],
  "give up": ["menyerah"],
  "surrenders": ["menyerah"],
  "yields": ["menyerah"],
  "bows": ["tunduk pada"],
  "stoops": ["membungkuk"],
  "kneels": ["berlutut"],
  "prostrates": ["sujud"],
  "cringes": ["merinding"],
  "fawns": ["menjilat"],
  "flatters": ["menyanjung"],
  "compliments": ["memuji"],
  "extols": ["memuji"],
  "lauds": ["memuji"],
  "magnifies": ["memperbesar"],
  "exalts": ["memuliakan"],
  "elevates": ["meningkatkan"],
  "hoists": ["mengangkat"],
  "heaves": ["mengangkat"],
  "flings": ["melempar"],
  "hurls": ["melempar"],
  "casts": ["melempar"],
  "pitches": ["melempar"],
  "chucks": ["melempar"],
  "lobs": ["melempar"],
  "projects": ["memproyeksikan"],
  "propels": ["mendorong"],
  "fires": ["menembak"],
  "blasts": ["meledakkan"],
  "bursts": ["meledak"],
  "pops": ["meletus"],
  "divides": ["membagi"],
  "parts": ["berpisah"],
  "separates": ["memisahkan"],
  "severs": ["memutuskan"],
  "cleaves": ["membelah"],
  "rends": ["merobek"],
  "chisels": ["memahat"],
  "engraves": ["mengukir"],
  "etches": ["mengukir"],
  "inscribes": ["menulisi"],
  "prints": ["mencetak"],
  "stamps": ["mengecap"],
  "brands": ["menandai"],
  "labels": ["melabeli"],
  "tags": ["menandai"],
  "tickets": ["menikete"],
  "styles": ["gaya"],
  "titles": ["judul"],
  "terms": ["istilah"],
  "designates": ["menunjuk"],
  "appoints": ["menunjuk"],
  "nominates": ["mencalonkan"],
  "elects": ["memilih"],
  "favors": ["mendukung"]
};

List<String> translateVerbList(List<dynamic> verbList) {
  List<String> result = [];
  for (var verbPart in verbList) {
    if (verbPart is String) {
      String translatedPart = verbPart;
      
      // Terjemahkan dengan mencocokkan kata kerja dalam kamus
      for (var entry in verbTranslations.entries) {
        final key = entry.key;
        final transList = entry.value;
        if (transList.isNotEmpty) {
          final trans = transList[0];
          
          // Ganti kata persis menggunakan RegExp kata
          final regExp = RegExp('\\b$key\\b', caseSensitive: false);
          if (regExp.hasMatch(translatedPart)) {
            translatedPart = translatedPart.replaceAll(regExp, trans);
          } else if (translatedPart.toLowerCase().trim() == key.toLowerCase()) {
            translatedPart = trans;
          }
        }
      }
      result.add(translatedPart);
    }
  }
  return result;
}

void main() {
  // 1. Load data.json
  final dataFile = File('assets/localization/data.json');
  if (!dataFile.existsSync()) {
    print('Error: assets/localization/data.json not found');
    return;
  }
  final dataList = json.decode(dataFile.readAsStringSync()) as List<dynamic>;

  // 2. Load en.json
  final enFile = File('assets/localization/cards/en.json');
  if (!enFile.existsSync()) {
    print('Error: assets/localization/cards/en.json not found');
    return;
  }
  final enMap = json.decode(enFile.readAsStringSync()) as Map<String, dynamic>;

  // 3. Load id.json
  final idFile = File('assets/localization/cards/id.json');
  if (!idFile.existsSync()) {
    print('Error: assets/localization/cards/id.json not found');
    return;
  }
  final idMap = json.decode(idFile.readAsStringSync()) as Map<String, dynamic>;

  // 4. Update data in maps
  int enCount = 0;
  int idCount = 0;

  for (var gesture in dataList) {
    final String idStr = gesture['id'].toString();
    final comparesList = gesture['compares'] as List<dynamic>;

    // a. Buat map clash_rules untuk English
    final Map<String, dynamic> enRules = {};
    // b. Buat map clash_rules untuk Indonesian
    final Map<String, dynamic> idRules = {};

    for (var comp in comparesList) {
      final String otherId = comp['other_gesture_id'].toString();
      final List<dynamic> verbList = comp['verb'] as List<dynamic>;

      enRules[otherId] = verbList;
      idRules[otherId] = translateVerbList(verbList);
    }

    // Injeksi ke enMap
    if (enMap.containsKey(idStr)) {
      final cardData = enMap[idStr] as Map<String, dynamic>;
      cardData['clash_rules'] = enRules;
      enCount++;
    }

    // Injeksi ke idMap
    if (idMap.containsKey(idStr)) {
      final cardData = idMap[idStr] as Map<String, dynamic>;
      cardData['clash_rules'] = idRules;
      idCount++;
    }
  }

  // 5. Simpan kembali en.json
  final JsonEncoder encoder = const JsonEncoder.withIndent('  ');
  enFile.writeAsStringSync(encoder.convert(enMap));
  print('Successfully updated assets/localization/cards/en.json for $enCount cards!');

  // 6. Simpan kembali id.json
  idFile.writeAsStringSync(encoder.convert(idMap));
  print('Successfully updated assets/localization/cards/id.json for $idCount cards!');
}
