name: my_rps_game
description: "RPS Card Game 101 Elements."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/localization/cards/
    - assets/localization/ui/
    - assets/images/background/
    - assets/images/cards/
    - assets/images/characters/

  fonts:
    - family: Familjen Grotesk
      fonts:
        - asset: assets/fonts/FamiljenGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/FamiljenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/FamiljenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FamiljenGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/FamiljenGrotesk-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/FamiljenGrotesk-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/FamiljenGrotesk-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/FamiljenGrotesk-BoldItalic.ttf
          style: italic
          weight: 700